### ISSUE TITLE
successful parallelization of RODEO

### ISSUE THREAD

**Issue by jbadomics** [the-mitchell-lab/rodeo#2]
Happy to report that RODEO can be successfully parallelized by partitioning each query into its own output directory, and creating symbolic links within that directory to the RODEO `.pl` scripts and Pfam database(s).

**Requirements:**
*   [GNU parallel](https://www.gnu.org/software/parallel/)

Within the RODEO parent directory, run:

```
cat accessions.txt | parallel -j 16 'mkdir {}_rodeo && cd {}_rodeo/ && for i in \
../Pfam-A.hmm* ../rodeo.pl ../toPeptides.pl ../translate.pl ../parameters_RODEO.txt; \
do ln -s ${i}; done && perl ./rodeo.pl {} -o ./{}.output.html -x -c ./parameters_RODEO.txt'
```

With 16 cores I was able to process 650 accessions in ~35 minutes. After the run is complete, symlinks can be removed with

```
find *_rodeo/ -type l | xargs rm
```

**Caveat**: this approach will create one HTML output for each accession (as opposed to the concatenated HTML produced by default).

**Comment by bkille** [comment]
@jbadomics , thanks for the contribution! We can add this to the README.md for rodeo, however, we'd advise you use the new version of [rodeo](https://github.com/the-mitchell-lab/rodeo2). It does the parallelization you described above, as well as a bunch of other niceties. If there's something missing in rodeo2, please open an issue and let us know.

Thanks!
